inherits:
  - utils:base
  - utils:no-design-checks
  - utils:c2cwsgiutils
  - utils:fix
  - utils:unsafe
  - duplicated

mypy:
  options:
    python-version: '3.9'

ruff:
  options:
    target-version: py39
